kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: webhook_demo
        # Send severity=webhook alerts to the webhook
          match:
            severity: webhook
          group_wait: 10s
          repeat_interval: 1m

    receivers:
    - name: webhook_demo
      webhook_configs:
      - url: https://webhook.site/cc9924bf-dd30-446c-955b-bfdfeafc71e6
